matrix:
  include:
  - os: osx
    osx_image: xcode9.2    # macOS 10.12 Sierra
  - os: osx
    osx_image: xcode11.2   # macOS 10.14 Mojave
  #- os: linux

language: cpp

notifications:
  email: false

sudo: required
dist: trusty

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install -y libtommath0 libtommath-dev
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./autogen.sh --enable-binreloc --prefix=/opt/firebird
      make -j4
      make dist
      tar xzvf gen/Firebird-[0-9]*.tar.gz
      (cd Firebird-[0-9]*; sudo ./install.sh -silent)
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export LIBTOOLIZE=glibtoolize
      export LIBTOOL=glibtool
      mkdir extern/icu-macos
      pushd extern/icu-macos
      wget https://github.com/unicode-org/icu/releases/download/release-59-2/icu4c-59_2-src.tgz
      wget https://github.com/unicode-org/icu/commit/24aeb9a5a5874f4ce5db912e30670ac3ae236971.patch
      tar xzvf icu4c-59_2-src.tgz
      ICU_INSTALL_PATH=`pwd`/install
      cd icu/source
      patch -p3 < ../../24aeb9a5a5874f4ce5db912e30670ac3ae236971.patch
      ./runConfigureICU MacOSX --prefix=$ICU_INSTALL_PATH
      #sudo make install
      make install
      popd
      export C_INCLUDE_PATH="$ICU_INSTALL_PATH/include:$C_INCLUDE_PATH"
      export CPLUS_INCLUDE_PATH="$ICU_INSTALL_PATH/include:$CPLUS_INCLUDE_PATH"
      #export LIBRARY_PATH="$ICU_INSTALL_PATH/lib:$LIBRARY_PATH"
      #export DYLD_LIBRARY_PATH="$ICU_INSTALL_PATH/lib:$DYLD_LIBRARY_PATH"
      #export CPPFLAGS="-stdlib=libc++"
      export CXX="g++ -stdlib=libc++"
      env
      mkdir -p gen/Release/firebird/lib
      cp $ICU_INSTALL_PATH/lib/*.dylib gen/Release/firebird/lib/
      find . -name utrans.h
      find . -name 'libicuuc*'
      LIBRARY_PATH="$ICU_INSTALL_PATH/lib:$LIBRARY_PATH" ./autogen.sh --with-builtin-tommath
      make -j4
      #(cd gen; make -B -f make.platform.postfix ICU_LOC="`pwd`/../extern/icu-macos/icu/source/lib/")
      (cd gen; make -B -f make.platform.postfix ICU_LOC="$ICU_INSTALL_PATH/lib/")
      (cd gen; make -B -f Makefile.install)
      find . -name '*.pkg'
    fi
