matrix:
  include:
  #- os: osx
  #  osx_image: xcode9.2    # macOS 10.12 Sierra
  - os: osx
    osx_image: xcode11.2   # macOS 10.14 Mojave
  #- os: linux

language: cpp

notifications:
  email: false

sudo: required
dist: trusty

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install -y libtommath0 libtommath-dev
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./autogen.sh --enable-binreloc --prefix=/opt/firebird
      make -j4
      make dist
      tar xzvf gen/Firebird-[0-9]*.tar.gz
      (cd Firebird-[0-9]*; sudo ./install.sh -silent)
    fi

    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cd tests
      mkdir -p out/exe out/lib1 out/lib2
      gcc -dynamiclib lib1.cpp -install_name @rpath/lib1/lib1.dylib -o out/lib1/lib1.dylib
      gcc -dynamiclib lib2.cpp -install_name @rpath/lib2/lib2.dylib -o out/lib2/lib2.dylib -Lout/lib1 -l1
      gcc exe1.cpp -Wl,-rpath,@executable_path/.. -o out/exe/exe1.out -Lout/lib2 -l2
      gcc exe1.cpp -Wl,-rpath,@loader_path/.. -o out/exe/exe2.out -Lout/lib2 -l2
      echo echo exe1
      ./out/exe/exe1.out
      echo echo exe2
      ./out/exe/exe2.out
      echo otool exe1
      otool -L out/exe/exe1.out
      echo otool exe2
      otool -L out/exe/exe2.out
      echo otool lib1
      otool -L out/lib1/lib1.dylib
      echo otool lib2
      otool -L out/lib2/lib2.dylib

      gcc -dynamiclib lib1.cpp -install_name @rpath/lib1b.dylib -o out/lib1/lib1b.dylib
      gcc -dynamiclib lib2.cpp -Wl,-rpath,@loader_path/../lib1 -install_name @rpath/lib2b.dylib -o out/lib2/lib2b.dylib -Lout/lib1 -l1b
      gcc exe1.cpp -Wl,-rpath,@loader_path/../lib2 -o out/exe/exe3.out -Lout/lib2 -l2b

      echo echo exe3
      ./out/exe/exe3.out
      echo otool exe3
      otool -L out/exe/exe3.out
      echo otool lib1b
      otool -L out/lib1/lib1b.dylib
      echo otool lib2b
      otool -L out/lib2/lib2b.dylib

      exit

      export LIBTOOLIZE=glibtoolize
      export LIBTOOL=glibtool

      mkdir extern/icu-macos
      pushd extern/icu-macos
      wget https://github.com/unicode-org/icu/releases/download/release-59-2/icu4c-59_2-src.tgz
      wget https://github.com/unicode-org/icu/commit/24aeb9a5a5874f4ce5db912e30670ac3ae236971.patch
      tar xzvf icu4c-59_2-src.tgz
      ICU_INSTALL_PATH=`pwd`/install
      cd icu/source
      patch -p3 < ../../24aeb9a5a5874f4ce5db912e30670ac3ae236971.patch
      ./runConfigureICU MacOSX --prefix=$ICU_INSTALL_PATH
      make -j4
      make install
      install_name_tool -id @rpath/libicuuc.dylib $ICU_INSTALL_PATH/lib/libicuuc.dylib
      install_name_tool -id @rpath/libicui18n.dylib $ICU_INSTALL_PATH/lib/libicui18n.dylib
      install_name_tool -id @rpath/libicudata.dylib $ICU_INSTALL_PATH/lib/libicudata.dylib
      install_name_tool -change libicudata.59.dylib @rpath/libicudata.59.dylib $ICU_INSTALL_PATH/lib/libicuuc.59.dylib
      install_name_tool -change libicudata.59.dylib @rpath/libicudata.59.dylib $ICU_INSTALL_PATH/lib/libicui18n.59.dylib
      install_name_tool -change libicuuc.59.dylib @rpath/libicuuc.59.dylib $ICU_INSTALL_PATH/lib/libicui18n.59.dylib
      popd
      mkdir -p gen/Release/firebird/lib
      mkdir -p gen/Debug/firebird/lib
      cp $ICU_INSTALL_PATH/lib/*.dylib gen/Release/firebird/lib/
      cp $ICU_INSTALL_PATH/lib/*.dylib gen/Debug/firebird/lib/

      export C_INCLUDE_PATH="$ICU_INSTALL_PATH/include:$C_INCLUDE_PATH"
      export CPLUS_INCLUDE_PATH="$ICU_INSTALL_PATH/include:$CPLUS_INCLUDE_PATH"

      LIBRARY_PATH="$ICU_INSTALL_PATH/lib:$LIBRARY_PATH" ./autogen.sh --with-builtin-tommath
      make -j4

      (cd gen; make -B -f make.platform.postfix ICU_LOC="$ICU_INSTALL_PATH/lib/")
      (cd gen; make -B -f Makefile.install)

      sudo installer -pkg gen/Release/*.pkg -verbose -target /
      find /Library/Frameworks/Firebird.framework
    fi
