name: Get Release Notes
description: Get Release Notes

runs:
  using: composite
  steps:
    - id: adjust-snapshot-buildno
      # FIXME:
      #if:
      #  github.repository == 'FirebirdSQL/firebird' &&
      #  (github.ref_type == 'branch' &&
      #    (github.ref_name == 'master' ||
      #      (startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '-release'))
      #    )
      #  ) ||
      #  false
      shell: bash
      run: |
        sed -i'' -e "s/SuffixKind=\(.*\)/SuffixKind=\"$(echo ${{ github.sha }} | cut -c 1-7)\"/" src/misc/writeBuildNum.sh
        mkdir gen
        src/misc/writeBuildNum.sh rebuildHeader
        # FIXME:
        cat src/jrd/build_no.h
