name: tzdata-update

on:
  schedule:
    # FIXME:
    - cron: '40 * * * *'

jobs:
  tzdata-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout ICU
        run: git clone --depth 1 https://github.com/unicode-org/icu-data.git -b master /tmp/icu-checkout

      - name: Check and update
        run: |
          VERSION=`ls /tmp/icu-checkout/tzdata/icunew/ -r1a |head -1`
          if [ "$VERSION" == "`cat tzdata/version.txt`" ]
          then
            exit
          fi

          echo $VERSION > tzdata/version.txt
          tzdata/update.sh
          export CREATE_PR=1

      - name: Create Pull Request
        if: env.CREATE_PR == '1'
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updata tzdata.
          title: Updata tzdata.
